services:
  - type: web
    name: school-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB
        sync: false
      - key: CLIENT
        sync: false
